# NumPy

What is NumPy?

NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.

At the core of the NumPy package, is the ndarray object. This encapsulates n-dimensional arrays of homogeneous data types


NumPy Arrays Vs Python Sequences

	• NumPy arrays have a fixed size at creation, unlike Python lists (which can grow dynamically). Changing the size of an ndarray will create a new array and delete the original.

	• The elements in a NumPy array are all required to be of the same data type, and thus will be the same size in memory.

	• NumPy arrays facilitate advanced mathematical and other types of operations on large numbers of data. Typically, such operations are executed more efficiently and with less code than is possible using Python’s built-in sequences.

	• A growing plethora of scientific and mathematical Python-based packages are using NumPy arrays; though these typically support Python-sequence input, they convert such input to NumPy arrays prior to processing, and they often output NumPy arrays.

In [2]:
import numpy as np

In [3]:
#1D Array Or Vector
list = [1, 2, 3, 4]

arr1 = np.array(list) 
arr1

array([1, 2, 3, 4])

In [9]:
arr1.shape

(4,)

In [10]:
list1 = [1, 2, 3, 4]
list2 = [1, 2, 3, 4]
list3 = [1, 2, 3, 4]
list4 = [1, 2, 3, 4]


#  2D Array Or Matrix
arry = np.array([list1, list2, list3, list4])
arry

array([[1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4]])

In [11]:
arry.shape

(4, 4)

In [12]:
# Custom Type ndArray
arr = np.array([1,2,3], dtype=int)
arr

array([1, 2, 3])

In [13]:
np.arange(1,13)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [14]:
# Reshape is Possible if Element can fit on that shape

np.arange(1,13).reshape(6,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [15]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [16]:
np.zeros((5,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [17]:
np.random.random((3,5))

array([[0.23901746, 0.69481665, 0.75889497, 0.99657479, 0.86065709],
       [0.69726354, 0.96653534, 0.85392878, 0.7983297 , 0.44613858],
       [0.97484325, 0.40513663, 0.11498753, 0.99070573, 0.39619858]])

In [18]:
np.linspace(-10,10,10)

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

# Array Attributes

In [19]:
a1 = np.arange(10, dtype=np.int64)
a2 = np.arange(12).reshape(4,3)
a5 = np.arange(12).reshape(4,3)
a3 = np.arange(16).reshape(2,4,2)
a4 = np.arange(16).reshape(2,2,2,2)

In [20]:
#  show Dimensions of Array
a4.ndim

4

In [21]:
#  shape of array
print(a1.shape)
print(a2.shape)
print(a3.shape)
print(a4.shape)

# size of Array
print(a1.size)

(10,)
(4, 3)
(2, 4, 2)
(2, 2, 2, 2)
10


In [22]:
# item size is show one element of array how many byte memory will take
a1.itemsize

8

In [23]:
# Datatype of Array
a1.dtype

dtype('int64')

In [24]:
# astype for change dtype of array
a2.astype(np.int64)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]], dtype=int64)

In [25]:
a3.astype(np.float64)

array([[[ 0.,  1.],
        [ 2.,  3.],
        [ 4.,  5.],
        [ 6.,  7.]],

       [[ 8.,  9.],
        [10., 11.],
        [12., 13.],
        [14., 15.]]])

In [26]:
# Sacaler Operatons
# it will apply to all element
a1 + 2
a1 * 8
a1 / 2

# Relation operatons
# it will compare all element of a2 with Relations
a2 < 40

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [27]:
# this is all vector opertaion will apply when shpe is same or follow Rules

a2 * a5
a2 + a5

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16],
       [18, 20, 22]])

# Numpy Functions

In [28]:
a1 = np.random.random(9).reshape((3,3))

# round decimal point , in this function decimal=0 so this is not show any number after decimal point
a1 = np.round(a1*100)
a1

array([[40., 27., 99.],
       [70., 74., 26.],
       [97., 45., 15.]])

In [29]:
# min, max, sum , prod

np.min(a1)
np.max(a1)
np.sum(a1)
np.prod(a1)

# give specifice col or row sum, max, min, prod
# col -> axis=0  row-> axis=1

np.max(a1,axis=0)
np.min(a1, axis=1)

array([27., 26., 15.])

In [30]:
# statical functions

np.mean(a1)
np.median(a1,axis = 0)
np.std(a1)
np.var(a1)

870.6172839506173

In [31]:
# trignometry function

np.sin(a1)

array([[ 0.74511316,  0.95637593, -0.99920683],
       [ 0.77389068, -0.98514626,  0.76255845],
       [ 0.37960774,  0.85090352,  0.65028784]])

In [32]:
# dot product / multiplecation of matrix
# this function follow matrix dot product rule also

a2 = np.arange(12).reshape(3,4)
a3 = np.arange(12,24).reshape(4,3)

np.dot(a2,a3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [33]:
# round => round to nearest integer
# floor => floor value
# ceil => give ceiling value
np.ceil(6.0)
np.floor(6.6)
np.round(6.4)

6.0

In [34]:
a1[0,0]

40.0

In [35]:
# slicing

In [36]:
# transpose
np.transpose(a1)
a1.T

array([[40., 70., 97.],
       [27., 74., 45.],
       [99., 26., 15.]])

In [37]:
# Learn in Web
# hstrack
# vstack

In [38]:
#Spliting

np.hsplit(a1,3)
# this per form when array have enouph row and col for split 
# example in can not split 3x3 array in two part

# split always divede in equal parts
np.vsplit(a1,3)

[array([[40., 27., 99.]]), array([[70., 74., 26.]]), array([[97., 45., 15.]])]